# Generated by Django 6.0.4 on 2026-04-22 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('shop', 'Shop'), ('cafe', 'Cafe')], default='restaurant', max_length=12)),
                ('currency', models.CharField(max_length=5)),
                ('background_image', models.FileField(blank=True, upload_to='system/files/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_tables', models.BooleanField(default=True)),
                ('enable_kitchen', models.BooleanField(default=True)),
                ('enable_inventory', models.BooleanField(default=False)),
                ('enable_barcode', models.BooleanField(default=False)),
                ('enable_variants', models.BooleanField(default=True)),
                ('enable_discounts', models.BooleanField(default=True)),
                ('enable_partial_payments', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_config', to='system_config.business')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Tax cannot be less than zero'), django.core.validators.MaxValueValidator(100, message='Tax is limited to 100%')])),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Service charge cannot be less than zero'), django.core.validators.MaxValueValidator(100, message='Service charge cannot be more than 100%')])),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_config', to='system_config.business')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='system_config.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'key'), name='unique_business_setting_key')],
            },
        ),
    ]
