# Generated by Django 5.2 on 2025-06-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='has_admin',
            new_name='is_admin',
        ),
    ]
