# Generated by Django 5.2 on 2025-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_table_status_alter_bill_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestatus',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
