# Generated by Django 5.2 on 2025-12-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_tablestatus_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablestatus',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablestatus',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('busy', 'Busy')], default='available'),
            preserve_default=False,
        ),
    ]
