# Generated by Django 5.2 on 2025-12-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_tablestatus_date_tablestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablestatus',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('busy', 'Busy')], default='available', max_length=23),
        ),
    ]
