# Generated by Django 5.2 on 2026-02-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_tablestatus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food_name',
            new_name='name',
        ),
    ]
