# Generated by Django 6.0.4 on 2026-05-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
        ('tables', '0007_rename_food_name_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='floor',
            new_name='group',
        ),
        migrations.CreateModel(
            name='TablesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('tables_type', models.CharField(choices=[('noraml', 'Normal'), ('reservation', 'Reservation'), ('buffet', 'Buffet')], default='noraml', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_groups', to='system_config.business')),
            ],
        ),
    ]
