# Generated by Django 6.0.4 on 2026-05-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_rename_floor_table_group_tablesgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tables.tablesgroup'),
        ),
    ]
