# Generated by Django 6.0.4 on 2026-05-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_alter_table_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
