# Generated by Django 6.0.4 on 2026-05-25 17:15

import django.db.models.deletion
import tables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_discount_alter_order_subtotal_and_more'),
        ('tables', '0010_delete_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[tables.models.validate_positive])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condiments', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('dine in', 'Dine in'), ('take out', 'Take out')], default='dine in', max_length=30)),
                ('is_ordered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
