# Generated by Django 6.0.4 on 2026-05-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_orderchild_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderChild',
        ),
    ]
