# Generated by Django 6.0.4 on 2026-05-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='system_config.business')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_config.business')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='products.modifiergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProuductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=130, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.FileField(blank=True, upload_to='product/images')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_config.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='products.prouductvariant'),
        ),
    ]
