# Generated by Django 6.0.4 on 2026-05-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProuductVariant',
            new_name='ProductVaraint',
        ),
    ]
