# Generated by Django 6.0.4 on 2026-05-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_prouductvariant_productvaraint'),
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVaraint',
            new_name='ProductVariant',
        ),
    ]
